apiVersion: v1
kind: Service
metadata:
  name: onlyoffice
spec:
  selector:
    app: onlyoffice
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    # - name: https
    #   port: 443
    #   targetPort: 443
    #   protocol: TCP
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: onlyoffice
spec:
  hosts:
    - onlyoffice.local-cluster.dev
  gateways:
    - onlyoffice-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: onlyoffice.default.svc.cluster.local
            port:
              number: 80
