apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlyoffice
  labels:
    app: onlyoffice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onlyoffice
  template:
    metadata:
      labels:
        app: onlyoffice
    spec:
      # hostAliases:
      # - ip: "172.18.0.200"
      #   hostnames:
      #   - "seafile.local-cluster.dev"
      containers:
      - name: onlyoffice
        image: trow.local-cluster.dev/documentserver-ca
        ports:
        - containerPort: 80
          name: http
        # - containerPort: 443
        #   name: https
        env:
        - name: NODE_EXTRA_CA_CERTS
          value: "/usr/local/share/ca-certificates/rootCA.crt"
        - name: JWT_ENABLED
          value: "true"
        - name: JWT_SECRET
          value: "XG4FcDp9Rvj8K2QwS5tZv6YbAa3uH1NmJ7eLkP0qOxIiUyVlWoEh"  # Replace with a strong key
      #   volumeMounts:
      #   - name: onlyoffice-logs
      #     mountPath: /var/log/onlyoffice
      #   - name: onlyoffice-data
      #     mountPath: /var/www/onlyoffice/Data
      # volumes:
      # - name: onlyoffice-logs
      #   persistentVolumeClaim:
      #     claimName: onlyoffice-logs-pvc
      # - name: onlyoffice-data
      #   persistentVolumeClaim:
      #     claimName: onlyoffice-data-pvc

# https://manual.seafile.com/11.0/deploy/only_office/
#https://helpcenter.onlyoffice.com/docs/installation/docs-community-install-docker.aspx