apiVersion: v1
kind: Service
metadata:
  name: sdoc-server
spec:
  selector:
    app: sdoc-server
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 7070
    - name: https
      protocol: TCP
      port: 443
      targetPort: 7070
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: seadoc
spec:
  hosts:
    - seadoc.acc.ricksdomein.nl
  gateways:
    - seadoc-gateway
  http:
    - match:
      - headers:
          Connection:
            exact: Upgrade
          Upgrade:
            exact: websocket
      route:
      - destination:
          host: sdoc-server.default.svc.cluster.local  # Changed to SeaDoc
          port:
            number: 80
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: sdoc-server.default.svc.cluster.local
            port:
              number: 80
