apiVersion: v1
kind: Service
metadata:
  name: sdoc-server
spec:
  selector:
    app: sdoc-server
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 7070
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: seadoc
spec:
  hosts:
    - seadoc.local-cluster.dev
  gateways:
    - seadoc-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: sdoc-server.default.svc.cluster.local
            port:
              number: 80
