apiVersion: apps/v1
kind: Deployment
metadata:
  name: seafile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seafile
  template:
    metadata:
      labels:
        app: seafile
      # annotations:
      #   inject-certs: "enabled"  
    spec:
      hostAliases:
      - ip: "172.18.0.200"
        hostnames:
        - "seafile.local-cluster.dev"
      - ip: "172.18.0.200"
        hostnames:
        - "seadoc.local-cluster.dev"
      containers:
        - name: seafile
          image: trow.local-cluster.dev/seafile-mc:12.0-latest-ca
          env:
            - name: JWT_PRIVATE_KEY
              value: "A3s85fwpaq2iipd5gY7TvwholJ23BedJDvfjfReu"  # Change this to a proper key
            - name: DB_HOST
              value: "mariadb"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "seafile" #db's password
            - name: DB_PASSWORD
              value: "db_dev" #db's password
            - name: DB_ROOT_PASSWD
              value: "db_dev" #db's password
            - name: SEAFILE_MYSQL_DB_CCNET_DB_NAME
              value: "ccnet_db"
            - name: SEAFILE_MYSQL_DB_SEAFILE_DB_NAME
              value: "seafile_db"
            - name: SEAFILE_MYSQL_DB_SEAHUB_DB_NAME
              value: "seahub_db"
            - name: TIME_ZONE
              value: "Europe/Amsterdam"
            - name: INIT_SEAFILE_ADMIN_EMAIL
              value: "admin@seafile.com" #admin email
            - name: INIT_SEAFILE_ADMIN_PASSWORD
              value: "admin_password" #admin password       
            - name: SEAFILE_SERVER_LETSENCRYPT
              value: "false"
            - name: ENABLE_SEADOC
              value: "false"
            - name: ENABLE_WIKI
              value: "false"
            - name: SEADOC_SERVER_URL
              value: "https://seadoc.local-cluster.dev"
            - name: SEAFILE_SERVER_HOSTNAME
              value: "seafile.local-cluster.dev"
            - name: SEAFILE_SERVER_PROTOCOL
              value: "https"    
            # - name: SEAFILE_SERVER_PROTOCOL
            #   value: "http"
            # - name: SEAFILE_SERVER_HOSTNAME
            #   value: "seafile.default.svc.cluster.local"
              
          ports:
            - containerPort: 80
            # - containerPort: 443
            #   name:  seafile-secure
          volumeMounts:
            - name: seafile-data
              mountPath: /shared
      volumes:
        - name: seafile-data
          persistentVolumeClaim:
            claimName: seafile-data
      restartPolicy: Always
      # to get image from protected repository
      imagePullSecrets:
        - name: regcred

