apiVersion: v1
kind: Service
metadata:
  name: seafile
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    # nodePort: 30000
  selector:
    app: seafile
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: seafile-virtualservice
spec:
  hosts:
    - "seafile.local-cluster.dev"
  gateways:
    - seafile-gateway
  http:
    # 1. WebSocket support — must come first
    - match:
        - uri:
            prefix: /socket.io
      rewrite:
        uri: /socket.io
      route:
        - destination:
            host: sdoc-server.default.svc.cluster.local
            port:
              number: 80

    # 2. SDoc path rewrite
    - match:
        - uri:
            prefix: /sdoc-server/
      rewrite:
        uri: /
      route:
        - destination:
            host: sdoc-server.default.svc.cluster.local
            port:
              number: 80

    # 3. Main Seafile UI
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: seafile.default.svc.cluster.local
            port:
              number: 80
