apiVersion: v1
kind: Service
metadata:
  name: seafile
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    # nodePort: 30000
  selector:
    app: seafile
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: seafile-virtualservice
spec:
  hosts:
    - "seafile.local-cluster.dev"
  gateways:
    - seafile-gateway
  http:
    # Route for SDoc under /sdoc-server/
    - match:
        - uri:
            prefix: /sdoc-server/
      rewrite:
        uri: /  # SDoc server sees "/" instead of "/sdoc-server/"
      route:
        - destination:
            host: sdoc-server.default.svc.cluster.local  # Adjust namespace
            port:
              number: 80
    # Route for main Seafile UI
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: seafile.default.svc.cluster.local  # Adjust namespace if needed
            port:
              number: 80
