apiVersion: v1
kind: Service
metadata:
  name: mariadb
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
