apiVersion: v1
kind: Service
metadata:
  name: memcached
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    app: memcached
  ports:
    - protocol: TCP
      port: 11211
      targetPort: 11211
