apiVersion: v1
kind: Service
metadata:
  name: onlyoffice
  labels:
    app: onlyoffice
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    app: onlyoffice
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP