apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdoc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdoc-server
  template:
    metadata:
      labels:
        app: sdoc-server
    spec:
      containers:
        - name: sdoc-server
          image: harbor.acc.ricksdomein.nl/library/sdoc-server:2.0-latest-ca
          ports:
            - containerPort: 80
          env:
            - name: NODE_EXTRA_CA_CERTS
              value: "/usr/local/share/ca-certificates/rootCA.crt"
            - name: SEAHUB_SERVICE_URL
              value: "https://seafile.acc.ricksdomein.nl"
            - name: JWT_PRIVATE_KEY
              value: "A3s85fwpaq2iipd5gY7TvwholJ23BedJDvfjfReu"
            - name: DB_HOST
              value: "mariadb"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "seafile"
            - name: DB_PASSWORD
              value: "db_dev"
            - name: DB_NAME
              value: "seahub_db"
            - name: TIME_ZONE
              value: "Europe/Amsterdam"
            - name: NON_ROOT
              value: "false"
          volumeMounts:
            - name: sdoc-server-storage
              mountPath: /shared
      volumes:
        - name: sdoc-server-storage
          persistentVolumeClaim:
            claimName: sdoc-server-storage
