apiVersion: v1
kind: Service
metadata:
  name: sdoc-server
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    app: sdoc-server
  ports:
    - name: http
      protocol: TCP
      port: 80