apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: seafile-tls
spec:
  secretName: seafile-https-cert
  dnsNames:
    - "seafile.acc.ricksdomein.nl"
  issuerRef:
    name: root-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seafile
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - seafile.acc.ricksdomein.nl
      secretName: seafile-https-cert
  rules:
    - host: seafile.acc.ricksdomein.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seafile
                port:
                  number: 80