apiVersion: v1
kind: Service
metadata:
  name: seafile
  labels:
    app: seafile
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: seafile
