# fetched via Vault
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: es-external-secret
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: es-secret-store
    kind: ClusterSecretStore
  target:
    name: app-secret-secret
  data:
  - secretKey: INIT_SEAFILE_ADMIN_EMAIL 
    remoteRef:
      key: seafile
      property: INIT_SEAFILE_ADMIN_EMAIL
  - secretKey: INIT_SEAFILE_ADMIN_PASSWORD 
    remoteRef:
      key: seafile
      property: INIT_SEAFILE_ADMIN_PASSWORD
  - secretKey: REDIS_PASSWORD 
    remoteRef:
      key: seafile
      property: REDIS_PASSWORD
  - secretKey: JWT_PRIVATE_KEY 
    remoteRef:
      key: seafile
      property: JWT_PRIVATE_KEY
  - secretKey: SEAFILE_MYSQL_DB_PASSWORD 
    remoteRef:
      key: seafile
      property: SEAFILE_MYSQL_DB_PASSWORD
  - secretKey: INIT_SEAFILE_MYSQL_ROOT_PASSWORD 
    remoteRef:
      key: seafile
      property: INIT_SEAFILE_MYSQL_ROOT_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: es-external-secret-2
spec:
  # ...
  target:
    name: seahub-settings
    template:
      templateFrom:
      - configMap:
          # name of the configmap to pull in
          name: seahub-settings
          # here you define the keys that should be used as template
          items:
          - key: seahub_settings.py
  data:
  - secretKey: OAUTH_CLIENT_ID
    remoteRef:
      key: seafile
      property: OAUTH_CLIENT_ID
  - secretKey: OAUTH_CLIENT_SECRET
    remoteRef:
      key: seafile
      property: OAUTH_CLIENT_SECRET