# Root CA Secret
apiVersion: v1
kind: Secret
metadata:
  name: root-cert  # Replace with the name for your root certificate secret
  namespace: ${NAMESPACE}  # Replace with your namespace
  # annotations:
  #   description: "Root CA for TLS Issuance"
  annotations:
    avp.kubernetes.io/path: "secret/data/tls/root-cert"
    # avp.kubernetes.io/secret-version: "1"
type: kubernetes.io/tls
stringData:
  tls.crt: |
    <tls.crt>
  tls.key: |
    <tls.key>
---
# Issuer
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-issuer  # Replace with the name for your issuer
  namespace: ${NAMESPACE}  # Replace with your namespace
spec:
  ca:
    secretName: root-cert  # This should match the secret name from above

---
# Certificate for the service (httpbin in this case)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-certificate  # Replace with the service name
  namespace: ${NAMESPACE}  # Replace with your namespace
spec:
  secretName: app-test-1-https-cert  # Replace with the secret name for the TLS certificate
  dnsNames:
    - app-test-1.local-cluster.dev  # Replace with your service's fully qualified domain name
  privateKey:
    rotationPolicy: Always
  issuerRef:
    name: ca-issuer  # This should match the name of your issuer
    kind: Issuer

---
# Service
apiVersion: v1
kind: Service
metadata:
 name: app-test-1 # Replace with your service name (e.g., httpbin)
 namespace: ${NAMESPACE} # Replace with your namespace
 labels:
   app: app-test-1 # Replace with your service name (e.g., httpbin)
   service: app-test-1 # Replace with your service name (e.g., httpbin)
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
  selector:
    app: app-test-1   # Replace with your service name (e.g., httpbin)

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-test-1 # Replace with your service name (e.g., httpbin)
  namespace: ${NAMESPACE} # Replace with your namespace
  annotations:
    link.argocd.argoproj.io/external-link: https://app-test-1.local-cluster.dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-test-1 # Replace with your service name (e.g., httpbin)
      version: v1
  template:
    metadata:
      labels:
        app: app-test-1
        version: v1 # Replace with your service name (e.g., httpbin)
    spec:
      containers:
        - name: nginx # Replace with your service name (e.g., httpbin)
          imagePullPolicy: IfNotPresent
          image: nginx:latest # Replace with your service image (e.g., docker.io/mccutchen/go-httpbin)
          ports:
            - containerPort: 8080

---
# Ingress (HTTPProxy)
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: app-test-1  # Replace with your service name (e.g., httpbin)
  namespace: ${NAMESPACE}  # Replace with your namespace
spec:
  virtualhost:
    fqdn: app-test-1.local-cluster.dev  # Replace with your service's fully qualified domain name
    tls:
      secretName: app-test-1-https-cert  # This should match the certificate secret name
  routes:
    - conditions:
      - prefix: /
      services:
        - name: app-test-1  # Replace with your service name (e.g., httpbin)
          port: 8000
