# app-test-1.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: app-test-1
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-test-1-tls
  namespace: app-test-1
spec:
  secretName: app-test-1-https-cert
  dnsNames:
    - "app-test-1.local-cluster.dev"
  issuerRef:
    name: root-ca-issuer
    kind: ClusterIssuer
---
apiVersion: v1
kind: Service
metadata:
  name: app-test-1
  namespace: app-test-1
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
  selector:
    app: app-test-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-test-1
  namespace: app-test-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-test-1
  template:
    metadata:
      labels:
        app: app-test-1
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: app-test-1-gateway
  namespace: app-test-1
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: app-test-1-https-cert
    hosts:
    - "app-test-1.local-cluster.dev"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: app-test-1
  namespace: app-test-1
spec:
  hosts:
  - "app-test-1.local-cluster.dev"
  gateways:
  - app-test-1-gateway
  http:
  - route:
    - destination:
        host: app-test-1
        port:
          number: 8000