---
# Root CA Secret
apiVersion: v1
kind: Secret
metadata:
  name: root-cert
  namespace: authentik
  annotations:
    avp.kubernetes.io/path: "secret/data/tls/root-cert"
type: kubernetes.io/tls
stringData:
  tls.crt: |
    <tls.crt>
  tls.key: |
    <tls.key>