apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpn-gateway
  labels:
    app: vpn-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpn-gateway
  template:
    metadata:
      labels:
        app: vpn-gateway
    spec:
      containers:
        - name: vpn
          image: qmcgaw/gluetun:latest
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
          env:
            - name: VPN_SERVICE_PROVIDER
              value: private internet access
            - name: OPENVPN_USER
              valueFrom:
                secretKeyRef:
                  name: vpn-secret
                  key: OPENVPN_USER
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vpn-secret
                  key: OPENVPN_PASSWORD
            - name: SERVER_REGIONS
              value: "Netherlands,Switzerland,Romania"
            # Security
            - name: FIREWALL
              value: "on"
            - name: KILL_SWITCH
              value: "on"
            # Port forwarding (if needed)
            - name: PORT_FORWARDING
              value: "off"
            # Health checking
            - name: HEALTH_SERVER_ADDRESS
              value: "0.0.0.0:9999"
            # Enable HTTP proxy
            - name: HTTPPROXY
              value: "on"
            - name: HTTPPROXY_LOG
              value: "on"
            - name: HTTPPROXY_PORT
              value: "8080"
          ports:
            - containerPort: 8080  # HTTP proxy
              name: http-proxy
            - containerPort: 9999  # Health check
              name: health
          livenessProbe:
            httpGet:
              path: /health
              port: 9999
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 9999
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vpn-secret
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: es-secret-store
    kind: ClusterSecretStore
  target:
    name: vpn-secret
  data:
  - secretKey: OPENVPN_USER 
    remoteRef:
      key: servarr/pia
      property: username
  - secretKey: OPENVPN_PASSWORD
    remoteRef:
      key: servarr/pia
      property: password
---
apiVersion: v1
kind: Service
metadata:
  name: vpn-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  selector:
    app: vpn-gateway
  ports:
    - name: http-proxy
      port: 8080
      targetPort: 8080
    - name: health
      port: 9999
      targetPort: 9999