apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpn-gateway
  labels:
    app: vpn-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpn-gateway
  template:
    metadata:
      labels:
        app: vpn-gateway
    spec:
      hostNetwork: true  # Add this line
      containers:
        - name: vpn
          image: qmcgaw/gluetun:latest
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
            privileged: true  # Add this for better device access
          env:
            # Update these environment variables to new names:
            - name: VPN_SERVICE_PROVIDER
              value: private internet access
            - name: OPENVPN_USER
              valueFrom:
                secretKeyRef:
                  name: vpn-secret
                  key: OPENVPN_USER
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vpn-secret
                  key: OPENVPN_PASSWORD
            - name: SERVER_REGIONS
              value: "Netherlands,Switzerland,Romania"
            
            # Updated DNS Configuration
            - name: DNS_ADDRESS  # Changed from DNS_PLAINTEXT_ADDRESS
              value: "127.0.0.1"  # Use local DNS instead of 1.1.1.1
            - name: DNS_SERVER  # Changed from DOT
              value: "on"
            - name: DNS_KEEP_NAMESERVER
              value: "off"
            
            # IPv6 Configuration
            - name: IPV6
              value: "off"
            
            # Security
            - name: FIREWALL
              value: "on"
            - name: KILL_SWITCH
              value: "on"
            
            # Updated Port forwarding
            - name: VPN_PORT_FORWARDING  # Changed from PORT_FORWARDING
              value: "off"
            
            # Updated HTTP proxy
            - name: HTTPPROXY
              value: "on"
            - name: HTTPPROXY_LOG
              value: "on"
            - name: HTTPPROXY_LISTENING_ADDRESS  # Changed from HTTPPROXY_PORT
              value: ":8080"
            
            # Add these for better stability:
            - name: HEALTH_TARGET_ADDRESS
              value: "cloudflare.com:443"
            - name: HEALTH_SERVER_LISTENING_ADDRESS
              value: "127.0.0.1:9999"
            
          ports:
            - containerPort: 8080
              name: http-proxy
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vpn-secret
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: es-secret-store
    kind: ClusterSecretStore
  target:
    name: vpn-secret
  data:
  - secretKey: OPENVPN_USER 
    remoteRef:
      key: servarr/pia
      property: username
  - secretKey: OPENVPN_PASSWORD
    remoteRef:
      key: servarr/pia
      property: password
---
apiVersion: v1
kind: Service
metadata:
  name: vpn-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  selector:
    app: vpn-gateway
  ports:
    - name: http-proxy
      port: 8080
      targetPort: 8080