apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpn-gateway
  labels:
    app: vpn-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpn-gateway
  template:
    metadata:
      labels:
        app: vpn-gateway
    spec:
      containers:
        - name: vpn
          image: qmcgaw/gluetun:latest
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          env:
            - name: VPN_SERVICE_PROVIDER
              value: pia
            - name: OPENVPN_USER
              valueFrom:
                secretKeyRef:
                  name: vpn-secret
                  key: OPENVPN_USER
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vpn-secret
                  key: OPENVPN_PASSWORD
            - name: VPN_PORT_FORWARDING
              value: "on"
            - name: FIREWALL
              value: "on"
            - name: SERVER_COUNTRIES
              value: "United States"
            # Add HTTP proxy configuration
            - name: HTTPPROXY
              value: "on"
            - name: HTTPPROXY_LOG
              value: "on"
            - name: HTTPPROXY_PORT
              value: "8080"
            # Add SOCKS5 proxy configuration  
            - name: SOCKS5
              value: "on"
            - name: SOCKS5_PORT
              value: "9090"
          ports:
            - containerPort: 8000 # Gluetun control port
            - containerPort: 8080 # HTTP proxy port
            - containerPort: 9090 # SOCKS5 proxy port
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
      restartPolicy: Always
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vpn-secret
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: es-secret-store
    kind: ClusterSecretStore
  target:
    name: vpn-secret
  data:
  - secretKey: OPENVPN_USER 
    remoteRef:
      key: servarr/pia
      property: username
  - secretKey: OPENVPN_PASSWORD
    remoteRef:
      key: servarr/pia
      property: password
---
apiVersion: v1
kind: Service
metadata:
  name: vpn-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  selector:
    app: vpn-gateway
  ports:
    - name: http-proxy
      port: 8080
      targetPort: 8080
    - name: socks5-proxy
      port: 9090
      targetPort: 9090
    - name: control
      port: 8000
      targetPort: 8000