---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyseer
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: es-secret-store
    kind: ClusterSecretStore
  target:
    name: jellyseer-secrets
  data:
    - secretKey: JELLYFIN_API_KEY
      remoteRef:
        key: servarr/jellyfin
        property: api_key

    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: servarr/jellyseer
        property: OIDC_CLIENT_ID
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: servarr/jellyseer
        property: OIDC_CLIENT_SECRET
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseer-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseer
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyseer
  template:
    metadata:
      labels:
        app: jellyseer
    spec:
      containers:
        - name: jellyseer
          image: ghcr.io/michaelhthomas/jellyseerr:feat-oidc-logi
          ports:
            - containerPort: 5055
          env:
            - name: TZ
              value: "Europe/Amsterdam"

            # --- Jellyfin connection ---
            - name: JELLYFIN_URL
              value: "https://jellyfin.acc.ricksdomein.nl"
            - name: JELLYFIN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: jellyseer-secrets
                  key: JELLYFIN_API_KEY

            # --- OIDC Provider ---
            - name: OIDC_ENABLED
              value: "true"

            - name: OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: jellyseer-secrets
                  key: OIDC_CLIENT_ID

            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jellyseer-secrets
                  key: OIDC_CLIENT_SECRET

            - name: OIDC_ISSUER
              value: "https://authentik.acc.ricksdomein.nl/application/o/jellyseer/"

            - name: OIDC_BASE_URL
              value: "https://jellyseer.acc.ricksdomein.nl"

            - name: OIDC_SCOPE
              value: "openid profile email"

            # # Example attributes Authentik sends
            # - name: OIDC_CLAIM_EMAIL
            #   value: "email"
            # - name: OIDC_CLAIM_NAME
            #   value: "name"
            # - name: OIDC_CLAIM_PREFERRED_USERNAME
            #   value: "preferred_username"
          volumeMounts:
            - name: config
              mountPath: /app/config

      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jellyseer-config
---
apiVersion: v1
kind: Service
metadata:
  name: jellyseer
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  selector:
    app: jellyseer
  ports:
    - name: http
      port: 5055
      targetPort: 5055
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyseer
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: jellyseer.acc.ricksdomein.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jellyseer
                port:
                  number: 5055
  tls:
    - hosts:
        - jellyseer.acc.ricksdomein.nl
      secretName: jellyseer-https-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyseer-tls
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  secretName: jellyseer-https-cert
  dnsNames:
    - jellyseer.acc.ricksdomein.nl
  issuerRef:
    name: root-ca-issuer
    kind: ClusterIssuer
