apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyfin
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: es-secret-store
    kind: ClusterSecretStore
  target:
    name: jellyfin-openid
  data:
  - secretKey: ClientId 
    remoteRef:
      key: servarr/jellyfin
      property: ClientId 
  - secretKey: ClientSecret
    remoteRef:
      key: servarr/jellyfin
      property: ClientSecret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyfin-tls
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  secretName: jellyfin-https-cert
  dnsNames:
    - "jellyfin.acc.ricksdomein.nl"
  issuerRef:
    name: root-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      securityContext:
        fsGroup: 1000
      # initContainers:
      # - name: install-sso-plugin
      #   image: curlimages/curl:latest
      #   command: 
      #     - /bin/sh
      #     - -c
      #     - |
      #       # Create plugins directory
      #       mkdir -p /config/plugins
            
      #       # Download the SSO plugin from the correct URL
      #       curl -L -o /config/plugins/jellyfin-plugin-sso.zip \
      #         "https://github.com/9p4/jellyfin-plugin-sso/releases/download/v4.0.0.3/sso-authentication_4.0.0.3.zip"
            
      #       # Extract the plugin
      #       unzip -o /config/plugins/jellyfin-plugin-sso.zip -d /config/plugins/
            
      #       # Clean up
      #       rm /config/plugins/jellyfin-plugin-sso.zip
        volumeMounts:
        - name: jellyfin-config
          mountPath: /config
      containers:
        - name: jellyfin
          image: harbor.acc.ricksdomein.nl/library/jellyfin:10.11.3-ca
          ports:
            - containerPort: 8096
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Amsterdam"
            - name: JELLYFIN_OpenIdConnect__Authority
              value: "https://authentik.acc.ricksdomein.nl/application/o/jellyfin/"
            - name: JELLYFIN_OpenIdConnect__ClientId
              valueFrom:
                secretKeyRef:
                  name: jellyfin-openid
                  key: ClientId
            - name: JELLYFIN_OpenIdConnect__ClientSecret
              valueFrom:
                secretKeyRef:
                  name: jellyfin-openid
                  key: ClientSecret
          volumeMounts:
            - name: jellyfin-config
              mountPath: /config
            - name: jellyfin-cache
              mountPath: /cache
            - name: qbittorrent-downloads
              mountPath: /library
      volumes:
        - name: jellyfin-config
          persistentVolumeClaim:
            claimName: jellyfin-config
        - name: jellyfin-cache
          persistentVolumeClaim:
            claimName: jellyfin-cache
        - name: qbittorrent-downloads
          persistentVolumeClaim:
            claimName: qbittorrent-downloads
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  selector:
    app: jellyfin
  ports:
    - name: http
      port: 8096
      targetPort: 8096
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    argocd.argoproj.io/sync-wave: "4"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - jellyfin.acc.ricksdomein.nl
      secretName: jellyfin-https-cert
  rules:
    - host: jellyfin.acc.ricksdomein.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jellyfin
                port:
                  number: 8096
