apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: restrict-media-apps-egress
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - prowlarr
          - qbittorrent
  policyTypes:
    - Egress
  egress:
    # 1️⃣ Allow traffic to VPN gateway pod
    - to:
        - podSelector:
            matchLabels:
              app: vpn-gateway
      ports:
        - protocol: UDP
          port: 1194
        - protocol: TCP
          port: 8080

    # 2️⃣ Allow AuthentiK traffic (in-cluster) - FIXED
    - to:
        - podSelector:
            matchLabels:
              app: authentik
      ports:
        - protocol: TCP
          port: 9000
    # ADD: Allow traffic to Authentik outpost
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: outpost  # typical outpost label
      ports:
        - protocol: TCP
          port: 9000

    # 3️⃣ Allow DNS
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53

    # 4️⃣ Allow Kubernetes API
    - to:
        - ipBlock:
            cidr: 10.96.0.0/12

    # 5️⃣ Allow LAN subnets
    - to:
        - ipBlock:
            cidr: 10.10.0.0/24
    - to:
        - ipBlock:
            cidr: 192.168.2.0/24

    # 6️⃣ Allow communication between Prowlarr and qBittorrent
    - to:
        - podSelector:
            matchLabels:
              app: prowlarr
    - to:
        - podSelector:
            matchLabels:
              app: qbittorrent
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-media-apps-ui-access
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - prowlarr
          - qbittorrent
  policyTypes:
    - Ingress
  ingress:
    # Allow from internal networks
    - from:
        - ipBlock:
            cidr: 10.0.0.0/8
        - ipBlock:
            cidr: 192.168.2.0/24
      ports:
        - protocol: TCP
          port: 9696
        - protocol: TCP
          port: 8080

    # Allow from ingress controller
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
          podSelector:
            matchLabels:
              app: ingress-nginx-controller
      ports:
        - protocol: TCP
          port: 9696
        - protocol: TCP
          port: 8080

    # ADD: Allow from Authentik outpost (CRITICAL FIX)
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: authentik  # authentik namespace
          podSelector:
            matchLabels:
              app.kubernetes.io/name: outpost  # outpost pod label
      ports:
        - protocol: TCP
          port: 9696
        - protocol: TCP
          port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ak-outpost-outpost
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: ExternalName
  externalName: ak-outpost-outpost.authentik.svc.cluster.local
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP