apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: restrict-media-apps-egress
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - prowlarr
          - qbittorrent
  policyTypes:
    - Egress
  egress:
    # 1️⃣ Allow traffic to VPN gateway pod
    - to:
        - podSelector:
            matchLabels:
              app: vpn-gateway
      ports:
        - protocol: UDP
          port: 1194  # or whatever port your VPN uses
        - protocol: TCP
          port: 8080  # for VPN admin UI if needed

    # 2️⃣ Allow AuthentiK traffic (in-cluster)
    - to:
        - podSelector:
            matchLabels:
              app: authentik
      ports:
        - protocol: TCP
          port: 9000  # authentik port

    # 3️⃣ Allow DNS (crucial for service discovery)
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53

    # 4️⃣ Allow Kubernetes API (for service discovery)
    - to:
        - ipBlock:
            cidr: 10.96.0.0/12  # typical Kubernetes service CIDR

    # 5️⃣ Allow LAN subnets
    - to:
        - ipBlock:
            cidr: 10.10.0.0/24
    - to:
        - ipBlock:
            cidr: 192.168.2.0/24

    # 6️⃣ Allow communication between Prowlarr and qBittorrent
    - to:
        - podSelector:
            matchLabels:
              app: prowlarr
    - to:
        - podSelector:
            matchLabels:
              app: qbittorrent
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-media-apps-ui-access
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - prowlarr
          - qbittorrent
  policyTypes:
    - Ingress
  ingress:
    # Allow from internal networks
    - from:
        - ipBlock:
            cidr: 10.0.0.0/8
        - ipBlock:
            cidr: 192.168.2.0/24
      ports:
        - protocol: TCP
          port: 9696  # Prowlarr UI
        - protocol: TCP
          port: 8080  # qBittorrent UI

    # Allow from ingress controller/load balancer
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx  # namespace name where nginx controller lives
          podSelector:
            matchLabels:
              app: ingress-nginx-controller  # pod label of your nginx controller
      ports:
        - protocol: TCP
          port: 9696  # Prowlarr UI
        - protocol: TCP
          port: 8080  # qBittorrent UI
---
apiVersion: v1
kind: Service
metadata:
  name: ak-outpost-outpost
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: ExternalName
  externalName: ak-outpost-outpost.authentik.svc.cluster.local
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP