apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-internet-for-media-apps
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - prowlarr
          - qbittorrent
  policyTypes:
    - Egress
  egress:
    # 1️⃣ Allow traffic to VPN gateway pod (all internet goes via VPN)
    - to:
        - podSelector:
            matchLabels:
              app: vpn-gateway

    # 2️⃣ Allow AuthentiK traffic
    # If AuthentiK is internal in-cluster:
    - to:
        - podSelector:
            matchLabels:
              app: authentik
    # If AuthentiK is external, add its public IP/subnet instead:
    # - to:
    #     - ipBlock:
    #         cidr: 203.0.113.25/32

    # 3️⃣ Optional: allow LAN subnets if needed (replace with your network)
    - to:
        - ipBlock:
            cidr: 10.10.0.0/24
    - to:
        - ipBlock:
            cidr: 192.168.2.0/24

    # ✅ DNS through VPN only (no leaks) - comment out if you want cluster DNS
    # - to:
    #     - namespaceSelector: {}
    #       ports:
    #         - protocol: UDP
    #           port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ui-access
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - prowlarr
          - qbittorrent
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: 10.0.0.0/8 
        - ipBlock:
            cidr: 192.168.2.0/24
      ports:
        - protocol: TCP
          port: 9696  # Prowlarr UI
        - protocol: TCP
          port: 8080  # qBittorrent UI
---
apiVersion: v1
kind: Service
metadata:
  name: ak-outpost-outpost
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: ExternalName
  externalName: ak-outpost-outpost.authentik.svc.cluster.local
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP