apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: restrict-media-apps-egress
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - prowlarr
          - qbittorrent
  policyTypes:
    - Egress
  egress:
    # 1️⃣ Allow traffic to VPN gateway pod AND through VPN
    - to:
        - podSelector:
            matchLabels:
              app: vpn-gateway
      ports:
        - protocol: UDP
          port: 1194
        - protocol: TCP
          port: 8080

    # 2️⃣ Allow ALL traffic through VPN (after connection established)
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
        - ipBlock:
            cidr: ::/0

    # 3️⃣ Allow DNS to specific DNS servers
    - to:
        - ipBlock:
            cidr: 10.96.0.10/32  # CoreDNS usually
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - ipBlock:
            cidr: 8.8.8.8/32
        - ipBlock:
            cidr: 1.1.1.1/32
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53

    # 4️⃣ Allow Kubernetes API
    - to:
        - ipBlock:
            cidr: 10.96.0.0/12

    # 5️⃣ Allow LAN subnets
    - to:
        - ipBlock:
            cidr: 10.10.0.0/24
    - to:
        - ipBlock:
            cidr: 192.168.2.0/24

    # 6️⃣ Allow communication between apps
    - to:
        - podSelector:
            matchLabels:
              app: prowlarr
    - to:
        - podSelector:
            matchLabels:
              app: qbittorrent

    # 7️⃣ Allow NTP (time synchronization)
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: UDP
          port: 123
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-media-apps-ui-access
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - prowlarr
          - qbittorrent
  policyTypes:
    - Ingress
  ingress:
    # Allow from internal networks
    - from:
        - ipBlock:
            cidr: 10.0.0.0/8
        - ipBlock:
            cidr: 192.168.2.0/24
      ports:
        - protocol: TCP
          port: 9696
        - protocol: TCP
          port: 8080

    # Allow from ingress controller (CORRECTED LABELS)
    - from:
        - namespaceSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
          podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
      ports:
        - protocol: TCP
          port: 9696
        - protocol: TCP
          port: 8080

    # Allow from Authentik outpost (CORRECTED LABELS)
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: authentik
          podSelector:
            matchLabels:
              app: authentik-outpost
      ports:
        - protocol: TCP
          port: 9696
        - protocol: TCP
          port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ak-outpost-outpost
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: ExternalName
  externalName: ak-outpost-outpost.authentik.svc.cluster.local
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP