apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: radarr-tls
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  secretName: radarr-https-cert
  dnsNames:
    - "radarr.acc.ricksdomein.nl"
  issuerRef:
    name: root-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: movies-pvc
#   annotations:
#     argocd.argoproj.io/sync-wave: "1"
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: longhorn
#   resources:
#     requests:
#       storage: 100Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: radarr-configmap
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  config.xml: |
    <Config>
      <BindAddress>*</BindAddress>
      <Port>7878</Port>
      <SslPort>9898</SslPort>
      <EnableSsl>False</EnableSsl>
      <LaunchBrowser>True</LaunchBrowser>
      <ApiKey>decd67e4991f4bafbd3476bb1828fc36</ApiKey>
      <AuthenticationMethod>External</AuthenticationMethod>
      <AuthenticationRequired>DisabledForLocalAddresses</AuthenticationRequired>
      <Branch>master</Branch>
      <LogLevel>debug</LogLevel>
      <SslCertPath></SslCertPath>
      <SslCertPassword></SslCertPassword>
      <UrlBase></UrlBase>
      <InstanceName>Radarr</InstanceName>
      <UpdateMechanism>Docker</UpdateMechanism>
    </Config>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      # InitContainer to create directories automatically
      initContainers:
        - name: init-download-dirs
          image: busybox
          command:
            - sh
            - -c
            - |
              mkdir -p /library/movies/ && \
              chown 1000:1000 -R /library && \
              chmod -R 775 /library

              if [ ! -s /config/config.xml ]; then
                echo "Seeding config.xml from ConfigMap"
                cp /seed/config.xml /config/config.xml
              fi
          volumeMounts:
            - name: qbittorrent-downloads
              mountPath: /library
            - name: radarr-conf
              mountPath: /seed
            - name: radarr-config
              mountPath: /config
      securityContext:
          fsGroup: 1000
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:latest
          ports:
            - containerPort: 7878
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Amsterdam"
          volumeMounts:
            - name: radarr-config
              mountPath: /config
            # - name: radarr-conf
            #   mountPath: /config/config.xml
            #   subPath: config.xml
            - name: qbittorrent-downloads
              mountPath: /library
            # - name: movies-pvc
            #   mountPath: /movies
      volumes:
        - name: radarr-config
          persistentVolumeClaim:
            claimName: radarr-config
        - name: radarr-conf
          configMap:
            name: radarr-configmap
        - name: qbittorrent-downloads
          persistentVolumeClaim:
            claimName: qbittorrent-downloads
        # - name: movies-pvc
        #   persistentVolumeClaim:
        #     claimName: movies-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  selector:
    app: radarr
  ports:
    - name: http
      port: 7878
      targetPort: 7878
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-url: |-
      http://ak-outpost-outpost.authentik.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
    nginx.ingress.kubernetes.io/auth-signin: |-
      https://prowlarr.acc.ricksdomein.nl/outpost.goauthentik.io/start?rd=$scheme://$http_host$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-response-headers: |-
      Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-entitlements,X-authentik-email,X-authentik-name,X-authentik-uid
    nginx.ingress.kubernetes.io/auth-snippet: |
      proxy_set_header X-Forwarded-Host $http_host;
      proxy_set_header X-Forwarded-Proto $scheme;
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    argocd.argoproj.io/sync-wave: "4"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - radarr.acc.ricksdomein.nl
      secretName: radarr-https-cert
  rules:
    - host: radarr.acc.ricksdomein.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: radarr
                port:
                  number: 7878
