apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  labels:
    app: qbittorrent
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
      # Gluetun VPN Sidecar
      - name: vpn
        image: qmcgaw/gluetun:latest
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - SYS_MODULE
        env:
          - name: VPN_SERVICE_PROVIDER
            value: private internet access
          - name: OPENVPN_USER
            valueFrom:
              secretKeyRef:
                name: vpn-secret
                key: OPENVPN_USER
          - name: OPENVPN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: vpn-secret
                key: OPENVPN_PASSWORD
          - name: SERVER_REGIONS
            value: "Netherlands,Switzerland,Romania"
          - name: DNS_PLAINTEXT_ADDRESS
            value: "1.1.1.1"
          - name: DNS_KEEP_NAMESERVER
            value: "off"
          - name: DOT
            value: "on"
          - name: IPV6
            value: "off"
          - name: FIREWALL
            value: "on"
          - name: KILL_SWITCH
            value: "on"
          - name: FIREWALL_OUTBOUND_SUBNETS
            value: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"  # Allow internal cluster traffic
          - name: FIREWALL_INPUT_PORTS
            value: "8080"  # Explicitly allow the web UI port
          - name: VPN_INPUT_PORTS
            value: "6881"  # Explicitly allow the web UI port
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "50m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "100m"
      
      # qBittorrent Container
      - name: qbittorrent
        image: lscr.io/linuxserver/qbittorrent:latest
        ports:
        - name: webui
          containerPort: 8080
        - name: torrent-tcp
          containerPort: 6881
          protocol: TCP
        - name: torrent-udp
          containerPort: 6881
          protocol: UDP
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "UTC"
        - name: WEBUI_PORT
          value: "8080"
        volumeMounts:
        - name: config
          mountPath: /config
        # - name: qbittorrent-conf
        #   mountPath: /config/qBittorrent/qBittorrent.conf
          subPath: qBittorrent.conf
        - name: downloads
          mountPath: /downloads
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: qbittorrent-config
      - name: downloads
        persistentVolumeClaim:
          claimName: qbittorrent-downloads
      - name: qbittorrent-conf
        configMap:
          name: qbittorrent-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: qbittorrent-configmap
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  qBittorrent.conf: |
    [Application]
    FileLogger\Age=1
    FileLogger\AgeType=1
    FileLogger\Backup=true
    FileLogger\DeleteOld=true
    FileLogger\Enabled=true
    FileLogger\MaxSizeBytes=66560
    FileLogger\Path=/config/qBittorrent/logs

    [BitTorrent]
    Session\DefaultSavePath=/downloads/
    Session\AddTorrentStopped=false
    Session\AlternativeGlobalDLSpeedLimit=1024
    Session\AlternativeGlobalUPSpeedLimit=1024
    Session\BandwidthSchedulerEnabled=true
    Session\ExcludedFileNames=
    Session\GlobalDLSpeedLimit=3072
    Session\GlobalUPSpeedLimit=2048
    Session\Port=6881
    Session\ProxyPeerConnections=false  # DISABLED - no proxy needed
    Session\QueueingSystemEnabled=true
    Session\SSL\Port=38686
    Session\ShareLimitAction=Stop
    Session\UseAlternativeGlobalSpeedLimit=true
    Session\UseUPnP=false

    [Core]
    AutoDeleteAddedTorrentFile=Never

    [Meta]
    MigrationVersion=8

    [Network]
    PortForwardingEnabled=false
    # REMOVED all proxy configuration
    Proxy\AuthEnabled=false
    Proxy\HostnameLookupEnabled=false
    Proxy\IP=
    Proxy\Password=
    Proxy\Port=8080
    Proxy\Profiles\BitTorrent=false
    Proxy\Profiles\Misc=false
    Proxy\Profiles\RSS=false
    Proxy\Type=None  # No proxy

    [Preferences]
    General\Locale=en
    General\StatusbarExternalIPDisplayed=true
    MailNotification\req_auth=true
    Scheduler\end_time=@Variant(\0\0\0\xf\x3\xa5\xd6\x80)
    WebUI\Address=0.0.0.0
    WebUI\AuthSubnetWhitelist=0.0.0.0/0
    WebUI\AuthSubnetWhitelistEnabled=true
    WebUI\LocalHostAuth=false
    WebUI\ServerDomains=*
    Downloads\SavePath=/downloads/
    Downloads\TempPath=/downloads/incomplete/
    Advanced\NetworkInterface=tun0
    Advanced\NetworkInterfaceName=tun0

    [RSS]
    AutoDownloader\DownloadRepacks=true
    AutoDownloader\SmartEpisodeFilter=s(\\d+)e(\\d+), (\\d+)x(\\d+), "(\\d{4}[.\\-]\\d{1,2}[.\\-]\\d{1,2})", "(\\d{1,2}[.\\-]\\d{1,2}[.\\-]\\d{4})"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vpn-secret
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: es-secret-store
    kind: ClusterSecretStore
  target:
    name: vpn-secret
  data:
  - secretKey: OPENVPN_USER 
    remoteRef:
      key: servarr/pia
      property: username
  - secretKey: OPENVPN_PASSWORD
    remoteRef:
      key: servarr/pia
      property: password
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-downloads
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Gi
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: qbittorrent-tls
spec:
  secretName: qbittorrent-https-cert
  dnsNames:
    - "qbittorrent.acc.ricksdomein.nl"
  issuerRef:
    name: root-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  type: ClusterIP
  selector:
    app: qbittorrent
  ports:
  - name: webui
    port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbittorrent-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-url: |-
      http://ak-outpost-outpost.authentik.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
    nginx.ingress.kubernetes.io/auth-signin: |-
      https://qbittorrent.acc.ricksdomein.nl/outpost.goauthentik.io/start?rd=$scheme://$http_host$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-response-headers: |-
      Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-entitlements,X-authentik-email,X-authentik-name,X-authentik-uid
    nginx.ingress.kubernetes.io/auth-snippet: |
      proxy_set_header X-Forwarded-Host $http_host;
      proxy_set_header X-Forwarded-Proto $scheme;
    argocd.argoproj.io/sync-wave: "7"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - qbittorrent.acc.ricksdomein.nl
      secretName: qbittorrent-https-cert
  rules:
    - host: qbittorrent.acc.ricksdomein.nl
      http:
        paths:
          - path: /outpost.goauthentik.io/
            pathType: Prefix
            backend:
              service:
                name: ak-outpost-outpost
                port:
                  number: 9000 
          - path: /
            pathType: Prefix
            backend:
              service:
                name: qbittorrent
                port:
                  number: 8080
--- 
apiVersion: v1
kind: Service
metadata:
  name: ak-outpost-outpost
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: ExternalName
  externalName: ak-outpost-outpost.authentik.svc.cluster.local
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP