apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonarr-tls
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  secretName: sonarr-https-cert
  dnsNames:
    - "sonarr.acc.ricksdomein.nl"
  issuerRef:
    name: root-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: series-pvc
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarr-configmap
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  config.xml: |
    <Config>
      <BindAddress>*</BindAddress>
      <Port>8989</Port>
      <SslPort>9899</SslPort>
      <EnableSsl>False</EnableSsl>
      <LaunchBrowser>True</LaunchBrowser>
      <ApiKey>dd26fe0eee584815b02808d9d0418ed6</ApiKey>
      <AuthenticationMethod>External</AuthenticationMethod>
      <AuthenticationRequired>DisabledForLocalAddresses</AuthenticationRequired>
      <Branch>master</Branch>
      <LogLevel>debug</LogLevel>
      <SslCertPath></SslCertPath>
      <SslCertPassword></SslCertPassword>
      <UrlBase></UrlBase>
      <InstanceName>Sonarr</InstanceName>
      <UpdateMechanism>Docker</UpdateMechanism>
    </Config>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      # InitContainer to create directories automatically
      initContainers:
        - name: init-download-dirs
          image: busybox
          command:
            - sh
            - -c
            - |
              mkdir -p /library/series/ && \
              chown 1000:1000 -R /library && \
              chmod -R 775 /library

              if [ ! -s /config/config.xml ]; then
                echo "Seeding config.xml from ConfigMap"
                cp /seed/config.xml /config/config.xml
              fi
          volumeMounts:
            - name: qbittorrent-downloads
              mountPath: /library
            - name: sonarr-conf
              mountPath: /seed
            - name: sonarr-config
              mountPath: /config
      securityContext:
          fsGroup: 1000
      containers:
        - name: sonarr
          image: lscr.io/linuxserver/sonarr:latest
          ports:
            - containerPort: 8989
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Amsterdam"
          volumeMounts:
            - name: sonarr-config
              mountPath: /config
            # - name: sonarr-conf
            #   mountPath: /config/config.xml
            #   subPath: config.xml
            - name: qbittorrent-downloads
              mountPath: /library
            - name: series-pvc
              mountPath: /series
      volumes:
        - name: sonarr-config
          persistentVolumeClaim:
            claimName: sonarr-config
        - name: sonarr-conf
          configMap:
            name: sonarr-configmap
        - name: qbittorrent-downloads
          persistentVolumeClaim:
            claimName: qbittorrent-downloads
        - name: series-pvc
          persistentVolumeClaim:
            claimName: series-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  selector:
    app: sonarr
  ports:
    - name: http
      port: 8989
      targetPort: 8989
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-url: |-
      http://ak-outpost-outpost.authentik.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
    nginx.ingress.kubernetes.io/auth-signin: |-
      https://sonarr.acc.ricksdomein.nl/outpost.goauthentik.io/start?rd=$scheme://$http_host$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-response-headers: |-
      Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-entitlements,X-authentik-email,X-authentik-name,X-authentik-uid
    nginx.ingress.kubernetes.io/auth-snippet: |
      proxy_set_header X-Forwarded-Host $http_host;
      proxy_set_header X-Forwarded-Proto $scheme;
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    argocd.argoproj.io/sync-wave: "4"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - sonarr.acc.ricksdomein.nl
      secretName: sonarr-https-cert
  rules:
    - host: sonarr.acc.ricksdomein.nl
      http:
        paths:
          - path: /outpost.goauthentik.io/
            pathType: Prefix
            backend:
              service:
                name: ak-outpost-outpost
                port:
                  number: 9000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sonarr
                port:
                  number: 8989
