# Certificate (cert-manager)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-vault-tls
  namespace: app-vault
spec:
  secretName: app-vault-https-cert
  dnsNames:
    - "app-vault.acc.ricksdomein.nl"
  issuerRef:
    name: root-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io

---
# Secret (fetched via Vault)
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: es-external-secret
  namespace: app-vault
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: es-secret-store
    kind: ClusterSecretStore
  target:
    name: test-vault-secret
  data:
  - secretKey: MY_TEST_SECRET 
    remoteRef:
      key: path_to_secret
      property: password

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-vault
  namespace: app-vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-vault
  template:
    metadata:
      labels:
        app: app-vault
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          env:
            - name: MY_TEST_SECRET
              valueFrom:
                secretKeyRef:
                  name: test-vault-secret
                  key: MY_TEST_SECRET

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: app-vault
  namespace: app-vault
  labels:
    app: app-vault
spec:
  selector:
    app: app-vault
  ports:
    - name: http
      port: 80
      targetPort: 80

---
# NGINX Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-vault
  namespace: app-vault
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - app-vault.acc.ricksdomein.nl
      secretName: app-vault-https-cert
  rules:
    - host: app-vault.acc.ricksdomein.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-vault
                port:
                  number: 80