# ---------------------------------------------------------------------
# TLS Certificate
# ---------------------------------------------------------------------
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vaultwarden-sso-tls
  namespace: vaultwarden
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  secretName: vaultwarden-sso-https-cert
  dnsNames:
    - "vault.acc.ricksdomein.nl"
  issuerRef:
    name: root-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io

---
# ---------------------------------------------------------------------
# Base Secrets from Vault
# ---------------------------------------------------------------------
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-sso-secrets
  namespace: vaultwarden
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: es-secret-store
    kind: ClusterSecretStore
  target:
    name: vaultwarden-sso-secret
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: vaultwarden/postgres
        property: username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: vaultwarden/postgres
        property: password
    - secretKey: VAULTWARDEN_ADMIN_TOKEN
      remoteRef:
        key: vaultwarden/admin
        property: token
    - secretKey: SMTP_USERNAME
      remoteRef:
        key: vaultwarden/smtp
        property: username
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: vaultwarden/smtp
        property: password
    - secretKey: SSO_CLIENT_ID
      remoteRef:
        key: vaultwarden/sso
        property: client_id
    - secretKey: SSO_CLIENT_SECRET
      remoteRef:
        key: vaultwarden/sso
        property: client_secret

---
# ---------------------------------------------------------------------
# DATABASE_URL Secret (FIXED - template only, no data entries)
# ---------------------------------------------------------------------
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-database-url
  namespace: vaultwarden
  annotations:
    argocd.argoproj.io/sync-wave: "1.5"
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: es-secret-store
    kind: ClusterSecretStore
  target:
    template:
      engineVersion: v2
      data:
        test: "{{ .username }}"               # If you are using plain manifests or gitops tools
        password: "{{ `{{ .username }}` }}"         # If you are using helm
        DATABASE_URL: "{{ `postgres://{{ .username }}:{{ .password }}@vaultwarden-postgres.vaultwarden.svc.cluster.local:5432/vaultwarden?sslmode=disable&connect_timeout=10` }}"         # If you are using helm
  data:
    - secretKey: username
      remoteRef:
        key: vaultwarden/postgres
        property: username
    - secretKey: password
      remoteRef:
        key: vaultwarden/postgres
        property: password

---
# ---------------------------------------------------------------------
# ConfigMap (non-sensitive values)
# ---------------------------------------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: vaultwarden-sso-config
  namespace: vaultwarden
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  DOMAIN: "https://vault.acc.ricksdomein.nl"
  SMTP_HOST: "smtp.acc.ricksdomein.nl"
  SMTP_FROM: "vaultwarden@acc.ricksdomein.nl"
  SMTP_PORT: "465"
  SMTP_SECURITY: "force_tls"
  SMTP_AUTH_MECHANISM: "Plain"
  SIGNUPS_ALLOWED: "false"
  SSO_ENABLED: "true"
  SSO_ONLY: "true"
  SSO_FRONTEND: "override"
  SSO_AUTHORITY: "https://authentik.ricksdomein.nl/application/o/vaultwarden/"
  SSO_ROLES_ENABLED: "true"
  SSO_ROLES_DEFAULT_TO_USER: "true"
  SSO_ROLES_TOKEN_PATH: "/application/o/userinfo/groups"

---
# ---------------------------------------------------------------------
# Vaultwarden Deployment
# ---------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden-sso
  namespace: vaultwarden
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden-sso
  template:
    metadata:
      labels:
        app: vaultwarden-sso
    spec:
      containers:
        - name: vaultwarden-sso
          image: timshel/vaultwarden:1.33.2-4
          env:
            # Sensitive secrets
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-database-url
                  key: DATABASE_URL
            - name: ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-sso-secret
                  key: VAULTWARDEN_ADMIN_TOKEN
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-sso-secret
                  key: SMTP_USERNAME
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-sso-secret
                  key: SMTP_PASSWORD
            - name: SSO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-sso-secret
                  key: SSO_CLIENT_ID
            - name: SSO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-sso-secret
                  key: SSO_CLIENT_SECRET
            # Non-sensitive config
            - name: DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: vaultwarden-sso-config
                  key: DOMAIN
            - name: SMTP_HOST
              valueFrom:
                configMapKeyRef:
                  name: vaultwarden-sso-config
                  key: SMTP_HOST
            - name: SMTP_FROM
              valueFrom:
                configMapKeyRef:
                  name: vaultwarden-sso-config
                  key: SMTP_FROM
            - name: SMTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: vaultwarden-sso-config
                  key: SMTP_PORT
            - name: SMTP_SECURITY
              valueFrom:
                configMapKeyRef:
                  name: vaultwarden-sso-config
                  key: SMTP_SECURITY
            - name: SMTP_AUTH_MECHANISM
              valueFrom:
                configMapKeyRef:
                  name: vaultwarden-sso-config
                  key: SMTP_AUTH_MECHANISM
            - name: SIGNUPS_ALLOWED
              valueFrom:
                configMapKeyRef:
                  name: vaultwarden-sso-config
                  key: SIGNUPS_ALLOWED
            - name: SSO_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: vaultwarden-sso-config
                  key: SSO_ENABLED
            - name: SSO_ONLY
              valueFrom:
                configMapKeyRef:
                  name: vaultwarden-sso-config
                  key: SSO_ONLY
            - name: SSO_FRONTEND
              valueFrom:
                configMapKeyRef:
                  name: vaultwarden-sso-config
                  key: SSO_FRONTEND
            - name: SSO_AUTHORITY
              valueFrom:
                configMapKeyRef:
                  name: vaultwarden-sso-config
                  key: SSO_AUTHORITY
            - name: SSO_ROLES_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: vaultwarden-sso-config
                  key: SSO_ROLES_ENABLED
            - name: SSO_ROLES_DEFAULT_TO_USER
              valueFrom:
                configMapKeyRef:
                  name: vaultwarden-sso-config
                  key: SSO_ROLES_DEFAULT_TO_USER
            - name: SSO_ROLES_TOKEN_PATH
              valueFrom:
                configMapKeyRef:
                  name: vaultwarden-sso-config
                  key: SSO_ROLES_TOKEN_PATH
          ports:
            - containerPort: 80

---
# ---------------------------------------------------------------------
# Vaultwarden Service
# ---------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden-sso
  namespace: vaultwarden
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  selector:
    app: vaultwarden-sso
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
# ---------------------------------------------------------------------
# Vaultwarden Ingress
# ---------------------------------------------------------------------
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vaultwarden-sso
  namespace: vaultwarden
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    argocd.argoproj.io/sync-wave: "4"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "vault.acc.ricksdomein.nl"
      secretName: vaultwarden-sso-https-cert
  rules:
    - host: "vault.acc.ricksdomein.nl"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vaultwarden-sso
                port:
                  number: 80
